import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowDownUp, Eye, File, FileText, Film, FolderInput, FolderPlus, Grid2X2, HardDriveDownload, Image, LayoutGrid, List, ListMusic, Music, Play, Search, Trash2, X } from 'lucide-react';
import { formatFileSize } from '../lib/api';
import { assignOfflineFolder, createOfflineFolder, listOfflineFolders, listOfflineMedia, listOfflinePlaylists, listOfflineTexts, OfflineFolder, OfflineMedia, OfflinePlaylist, OfflineText, OFFLINE_CHANGED_EVENT, offlinePlaybackFile, offlinePlaylistFiles, removeOfflineMedia, removeOfflinePlaylist, removeOfflineText } from '../lib/offline';
import { useAppStore } from '../lib/store';
import CustomSelect from './CustomSelect';

type Filter = 'all'|'playlist'|'audio'|'video'|'image'|'text'|'document';
type Sort = 'date'|'name'|'size';
type ViewMode = 'list'|'grid'|'dense';
type DeleteTarget = { kind:'playlist'|'media'|'text'; id:number; name:string };
type MoveTarget = DeleteTarget;

export default function DownloadsPage() {
 const [items,setItems]=useState<OfflineMedia[]>([]), [texts,setTexts]=useState<OfflineText[]>([]), [playlists,setPlaylists]=useState<OfflinePlaylist[]>([]), [folders,setFolders]=useState<OfflineFolder[]>([]);
 const [filter,setFilter]=useState<Filter>('all'), [query,setQuery]=useState(''), [sort,setSort]=useState<Sort>('date'), [sortDirection,setSortDirection]=useState<'asc'|'desc'>('desc'), [showSort,setShowSort]=useState(false);
 const [viewMode,setViewMode]=useState<ViewMode>(()=>(localStorage.getItem('komod-download-view') as ViewMode)||'list');
 const [deleteTarget,setDeleteTarget]=useState<DeleteTarget|null>(null), [loading,setLoading]=useState(true);
 const [folderFilter,setFolderFilter]=useState('all'), [showNewFolder,setShowNewFolder]=useState(false), [newFolderName,setNewFolderName]=useState(''), [moveTarget,setMoveTarget]=useState<MoveTarget|null>(null);
 const [moveFolderSelection,setMoveFolderSelection]=useState('root');
 const {setContentPreviewFile,startQueue,addToast}=useAppStore();
 const load=useCallback(async()=>{try{const [media,notes,lists,offlineFolders]=await Promise.all([listOfflineMedia(),listOfflineTexts(),listOfflinePlaylists(),listOfflineFolders()]);setItems(media);setTexts(notes);setPlaylists(lists);setFolders(offlineFolders.sort((a,b)=>a.name.localeCompare(b.name,'fa')));}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();window.addEventListener(OFFLINE_CHANGED_EVENT,load);return()=>window.removeEventListener(OFFLINE_CHANGED_EVENT,load)},[load]);
 const counts:Record<Filter,number>={all:playlists.length+items.length+texts.length,playlist:playlists.length,audio:items.filter(x=>x.file.file_type==='audio').length,video:items.filter(x=>x.file.file_type==='video').length,image:items.filter(x=>x.file.file_type==='image').length,text:texts.length,document:items.filter(x=>x.file.file_type==='document').length};
 const filters:Array<[Filter,string,typeof File]>=[['all','همه',HardDriveDownload],['playlist','پلی‌لیست',ListMusic],['audio','صدا',Music],['video','ویدیو',Film],['image','عکس',Image],['text','متن',FileText],['document','فایل',File]];
 const needle=query.trim().toLocaleLowerCase('fa');
 const compare=(a:{name:string;savedAt:string;size:number},b:{name:string;savedAt:string;size:number})=>{const value=sort==='name'?a.name.localeCompare(b.name,'fa'):sort==='size'?a.size-b.size:a.savedAt.localeCompare(b.savedAt);return sortDirection==='asc'?value:-value};
 const inFolder=(item:{folderId?:string|null})=>folderFilter==='all'||(folderFilter==='root'?!item.folderId:item.folderId===folderFilter);
 const visiblePlaylists=useMemo(()=>(filter==='all'||filter==='playlist'?playlists:[]).filter(inFolder).filter(x=>!needle||x.name.toLocaleLowerCase('fa').includes(needle)).sort((a,b)=>compare({name:a.name,savedAt:a.savedAt,size:0},{name:b.name,savedAt:b.savedAt,size:0})),[playlists,filter,folderFilter,needle,sort,sortDirection]);
 const visibleTexts=useMemo(()=>(filter==='all'||filter==='text'?texts:[]).filter(inFolder).filter(x=>!needle||x.file.file_name.toLocaleLowerCase('fa').includes(needle)).sort((a,b)=>compare({name:a.file.file_name,savedAt:a.savedAt,size:new Blob([a.content]).size},{name:b.file.file_name,savedAt:b.savedAt,size:new Blob([b.content]).size})),[texts,filter,folderFilter,needle,sort,sortDirection]);
 const visibleMedia=useMemo(()=>(filter==='all'?items:items.filter(x=>x.file.file_type===filter)).filter(inFolder).filter(x=>!needle||x.file.file_name.toLocaleLowerCase('fa').includes(needle)).sort((a,b)=>compare({name:a.file.file_name,savedAt:a.savedAt,size:a.blob.size},{name:b.file.file_name,savedAt:b.savedAt,size:b.blob.size})),[items,filter,folderFilter,needle,sort,sortDirection]);
 const scopedCount=visiblePlaylists.length+visibleTexts.length+visibleMedia.length, scopedSize=visibleMedia.reduce((s,x)=>s+x.blob.size,0)+visibleTexts.reduce((s,x)=>s+new Blob([x.content]).size,0);
 const play=async(item:OfflineMedia)=>{if(['audio','video'].includes(item.file.file_type)){const playable=visibleMedia.filter(x=>['audio','video'].includes(x.file.file_type));startQueue(await Promise.all(playable.map(offlinePlaybackFile)),Math.max(0,playable.findIndex(x=>x.id===item.id)));}else if(item.file.file_type==='image')setContentPreviewFile({...item.file,stream_url:URL.createObjectURL(item.blob)});else window.open(URL.createObjectURL(item.blob),'_blank','noopener,noreferrer')};
 const playPlaylist=async(p:OfflinePlaylist)=>{const files=await offlinePlaylistFiles(p);if(!files.length)return addToast('هیچ فایل آفلاینی از این پلی‌لیست باقی نمانده.','error');if(files.length<p.totalCount)addToast(`${(p.totalCount-files.length).toLocaleString('fa-IR')} فایل موجود نبود و رد شد.`);startQueue(files,0)};
 const confirmDelete=async()=>{if(!deleteTarget)return;if(deleteTarget.kind==='playlist')await removeOfflinePlaylist(deleteTarget.id);else if(deleteTarget.kind==='text')await removeOfflineText(deleteTarget.id);else await removeOfflineMedia(deleteTarget.id);setDeleteTarget(null);addToast('نسخه آفلاین از این دستگاه حذف شد.')};
 const createFolder=async()=>{try{const folder=await createOfflineFolder(newFolderName);setNewFolderName('');setShowNewFolder(false);setFolderFilter(folder.id);addToast('پوشه دانلود ساخته شد.');}catch(error){addToast(error instanceof Error?error.message:'ساخت پوشه انجام نشد.','error')}};
 const moveToFolder=async(folderId:string|null)=>{if(!moveTarget)return;await assignOfflineFolder(moveTarget.kind,moveTarget.id,folderId);setMoveTarget(null);addToast('به پوشه دانلود منتقل شد.');};
 const layout=viewMode==='list'?'space-y-2':viewMode==='grid'?'grid grid-cols-2 gap-3 md:grid-cols-3':'grid grid-cols-3 gap-2 sm:grid-cols-4 lg:grid-cols-6';
 return <div className="mx-auto w-full max-w-5xl p-4 pb-28 sm:p-6 md:pb-8 lg:p-8">
  <header><p className="text-xs font-semibold text-primary-300">📥 بی‌اینترنت هم کنارتن</p><h1 className="mt-1 text-3xl font-bold">دانلودها</h1><div className="mt-4 grid grid-cols-2 gap-2 sm:max-w-sm"><Stat label="موارد این بخش" value={`${scopedCount.toLocaleString('fa-IR')} مورد`}/><Stat label="حجم روی دستگاه" value={formatFileSize(scopedSize)}/></div></header>
  <div className="mt-5 grid grid-cols-7 gap-1 rounded-2xl border border-white/[.07] bg-dark-900/70 p-1">{filters.map(([value,label,Icon])=><button key={value} title={`${label} (${counts[value].toLocaleString('fa-IR')})`} onClick={()=>setFilter(value)} className={`flex h-11 items-center justify-center rounded-xl ${filter===value?'bg-primary-500/20 text-primary-200':'text-dark-400 hover:bg-white/[.04]'}`}><Icon className="h-4 w-4 sm:h-5 sm:w-5"/></button>)}</div>
  <div className="mt-3 flex items-center gap-2"><CustomSelect className="min-w-0 flex-1" value={folderFilter} onChange={setFolderFilter} options={[{value:'all',label:'همه پوشه‌های دانلود'},{value:'root',label:'بدون پوشه'},...folders.map(folder=>({value:folder.id,label:`📁 ${folder.name}`}))]}/><button className="btn-secondary flex h-11 shrink-0 items-center gap-2 px-3 text-xs" onClick={()=>setShowNewFolder(true)}><FolderPlus className="h-4 w-4"/><span className="hidden sm:inline">پوشه تازه</span></button></div>
  <div className="mt-3 flex items-center gap-1 rounded-2xl border border-white/[.07] bg-dark-900/70 p-1.5"><label className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute right-3 top-1/2 z-10 h-4 w-4 -translate-y-1/2 text-dark-500"/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-10 w-full rounded-xl bg-transparent pr-10 pl-3 text-sm outline-none" placeholder="جست‌وجو"/></label><div className="relative"><Tool active={showSort} title="مرتب‌سازی" onClick={()=>setShowSort(v=>!v)}><ArrowDownUp/></Tool>{showSort&&<div className="absolute left-0 top-full z-40 mt-2 w-44 rounded-2xl border border-white/10 bg-dark-900 p-1.5 shadow-2xl">{([['date','تاریخ ذخیره'],['name','نام'],['size','حجم']] as [Sort,string][]).map(([v,l])=><button key={v} onClick={()=>{if(sort===v)setSortDirection(direction=>direction==='asc'?'desc':'asc');else{setSort(v);setSortDirection(v==='name'?'asc':'desc')}setShowSort(false)}} className={`flex w-full items-center justify-between rounded-xl px-3 py-2 text-right text-sm ${sort===v?'bg-primary-500/15 text-primary-200':'text-dark-300 hover:bg-white/[.05]'}`}><span>{l}</span>{sort===v&&<span>{sortDirection==='asc'?'↑':'↓'}</span>}</button>)}</div>}</div><span className="h-6 w-px bg-white/[.08]"/>{([['list',List],['grid',LayoutGrid],['dense',Grid2X2]] as [ViewMode,typeof List][]).map(([mode,Icon])=><Tool key={mode} active={viewMode===mode} title={mode==='list'?'لیستی':mode==='grid'?'کارتی':'کاشی کوچک'} onClick={()=>{setViewMode(mode);localStorage.setItem('komod-download-view',mode)}}><Icon/></Tool>)}</div>
  {loading?<div className="mt-7 h-32 animate-pulse rounded-2xl bg-dark-800"/>:<div className={`mt-5 ${layout}`}>{visiblePlaylists.map(p=><DownloadRow view={viewMode} key={`p-${p.id}`} icon={<ListMusic/>} name={p.name} meta={`${p.fileIds.length.toLocaleString('fa-IR')} فایل آفلاین`} onOpen={()=>void playPlaylist(p)} onMove={()=>setMoveTarget({kind:'playlist',id:p.id,name:p.name})} onDelete={()=>setDeleteTarget({kind:'playlist',id:p.id,name:p.name})}/>)}{visibleTexts.map(x=><DownloadRow view={viewMode} key={`t-${x.id}`} icon={<FileText/>} name={x.file.file_name} meta={x.id<0?'در انتظار همگام‌سازی':'یادداشت آفلاین'} openIcon={<Eye/>} onOpen={()=>setContentPreviewFile(x.file)} onMove={()=>setMoveTarget({kind:'text',id:x.id,name:x.file.file_name})} onDelete={()=>setDeleteTarget({kind:'text',id:x.id,name:x.file.file_name})}/>)}{visibleMedia.map(x=><DownloadRow view={viewMode} key={`m-${x.id}`} icon={<TypeIcon type={x.file.file_type}/>} name={x.file.file_name} meta={formatFileSize(x.blob.size)} openIcon={x.file.file_type==='image'?<Eye/>:undefined} onOpen={()=>void play(x)} onMove={()=>setMoveTarget({kind:'media',id:x.id,name:x.file.file_name})} onDelete={()=>setDeleteTarget({kind:'media',id:x.id,name:x.file.file_name})}/>)}{!scopedCount&&<div className="col-span-full rounded-3xl border border-dashed border-white/10 py-14 text-center"><HardDriveDownload className="mx-auto h-10 w-10 text-dark-600"/><h2 className="mt-4 font-bold">اینجا فعلاً خالیه</h2><p className="mt-2 text-sm text-dark-500">از منوی فایل یا پلی‌لیست، «ذخیره آفلاین» را بزن.</p></div>}</div>}
  {showNewFolder&&<div className="fixed inset-0 z-[180] flex items-center justify-center bg-black/70 p-4" onClick={()=>setShowNewFolder(false)}><div className="w-full max-w-sm rounded-3xl border border-white/10 bg-dark-900 p-5" onClick={event=>event.stopPropagation()}><h2 className="font-bold">پوشه تازه در دانلودها</h2><input autoFocus value={newFolderName} onChange={event=>setNewFolderName(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')void createFolder()}} className="input mt-4 w-full" placeholder="نام پوشه"/><div className="mt-4 flex gap-2"><button disabled={!newFolderName.trim()} className="btn-primary flex-1" onClick={()=>void createFolder()}>ساخت پوشه</button><button className="btn-secondary" onClick={()=>setShowNewFolder(false)}>لغو</button></div></div></div>}
  {moveTarget&&<div className="fixed inset-0 z-[180] flex items-end justify-center bg-black/70 p-4 sm:items-center" onClick={()=>setMoveTarget(null)}><div className="w-full max-w-sm rounded-3xl border border-white/10 bg-dark-900 p-5" onClick={event=>event.stopPropagation()}><h2 className="font-bold">انتقال به پوشه دانلود</h2><p dir="auto" className="mt-1 truncate text-xs text-dark-400">{moveTarget.name}</p><CustomSelect className="mt-4" label="پوشه مقصد" value={moveFolderSelection} onChange={setMoveFolderSelection} options={[{value:'root',label:'📥 بدون پوشه'},...folders.map(folder=>({value:folder.id,label:`📁 ${folder.name}`}))]}/><div className="mt-4 flex gap-2"><button className="btn-primary flex-1" onClick={()=>void moveToFolder(moveFolderSelection==='root'?null:moveFolderSelection)}>انتقال</button><button className="btn-secondary" onClick={()=>setMoveTarget(null)}>لغو</button></div></div></div>}
  {deleteTarget&&<div className="fixed inset-0 z-[180] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" onClick={()=>setDeleteTarget(null)}><div className="w-full max-w-sm rounded-3xl border border-white/10 bg-dark-900 p-5" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-red-500/10 text-red-300"><Trash2/></span><div className="min-w-0 flex-1"><h2 className="font-bold">از دانلودها حذف بشه؟</h2><p className="mt-1 truncate text-xs text-dark-400">{deleteTarget.name}</p></div><button className="btn-icon" onClick={()=>setDeleteTarget(null)}><X/></button></div><p className="mt-4 text-sm leading-6 text-dark-300">نسخه آفلاین پاک می‌شود و فایل اصلی داخل کمد می‌ماند.</p><div className="mt-5 flex gap-2"><button className="flex-1 rounded-xl bg-red-500 px-4 py-2.5 font-semibold" onClick={()=>void confirmDelete()}>حذف</button><button className="btn-secondary flex-1" onClick={()=>setDeleteTarget(null)}>بی‌خیال</button></div></div></div>}
 </div>
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/[.07] bg-dark-900/70 p-3"><span className="block text-[11px] text-dark-500">{label}</span><strong className="mt-1 block text-lg text-primary-200">{value}</strong></div>}
function Tool({active,title,onClick,children}:{active:boolean;title:string;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} title={title} className={`flex h-9 w-9 items-center justify-center rounded-lg [&>svg]:h-4 [&>svg]:w-4 ${active?'bg-primary-500/20 text-primary-200':'text-dark-400 hover:bg-white/[.05]'}`}>{children}</button>}
function TypeIcon({type}:{type:string}){const Icon=type==='audio'?Music:type==='video'?Film:type==='image'?Image:File;return <Icon/>}
function DownloadRow({icon,name,meta,openIcon,onOpen,onMove,onDelete,view}:{icon:React.ReactNode;name:string;meta:string;openIcon?:React.ReactNode;onOpen:()=>void;onMove:()=>void;onDelete:()=>void;view:ViewMode}){const tiled=view!=='list';return <article className={`${tiled?'flex flex-col text-center':'flex items-center'} gap-3 rounded-2xl border border-white/[.07] bg-dark-900/65 ${view==='dense'?'p-2':'p-3'}`}><button onClick={onOpen} className={`flex shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-primary-500/20 to-pink-500/10 text-primary-300 [&>svg]:h-5 [&>svg]:w-5 ${tiled?'h-16 w-full':'h-12 w-12'}`}>{icon}</button><div className="min-w-0 flex-1"><strong dir="auto" className="block truncate text-sm">{name}</strong><small className="mt-1 block truncate text-dark-500">{meta}</small></div><div className="flex justify-center"><button onClick={onOpen} className="btn-icon">{openIcon||<Play/>}</button><button onClick={onMove} title="انتقال به پوشه" className="btn-icon"><FolderInput/></button><button onClick={onDelete} className="btn-icon text-red-300"><Trash2/></button></div></article>}
