import { useEffect, useMemo, useState } from 'react';
import { DndContext, DragEndEvent, DragOverlay, PointerSensor, TouchSensor, closestCenter, useSensor, useSensors } from '@dnd-kit/core';
import { SortableContext, arrayMove, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { ArrowDownUp, Check, ChevronDown, ChevronRight, DownloadCloud, Film, GripVertical, Image, LayoutGrid, List, MoreVertical, Music, Pencil, Play, Plus, RefreshCw, Save, Search, Share2, Shuffle, Trash2, Upload, X } from 'lucide-react';
import { formatDuration, Playlist, PlaylistItem, PlaylistSummary, useAddPlaylistItems, useCreatePlaylist, useDeletePlaylist, useFiles, useFolders, usePlaylist, usePlaylists, useRemovePlaylistItem, useReorderPlaylist, useShufflePlaylist, useUpdatePlaylist, useUploadFile } from '../lib/api';
import { useAppStore } from '../lib/store';
import CustomSelect from './CustomSelect';
import { saveFileOffline } from '../lib/offline';

type Kind = 'all' | 'audio' | 'video';
const telegram = () => (window as Window & { Telegram?: { WebApp?: any } }).Telegram?.WebApp;
const openPath = (path: string) => { if (location.pathname !== path) history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); };

export default function PlaylistBrowser() {
    const [path, setPath] = useState(location.pathname);
    const selectedId = Number(path.match(/^\/playlist\/(\d+)/)?.[1]) || null;
    useEffect(() => { const sync = () => setPath(location.pathname); addEventListener('popstate', sync); return () => removeEventListener('popstate', sync); }, []);
    useEffect(() => {
        const back = telegram()?.BackButton;
        if (!back || !selectedId) return;
        const handler = () => openPath('/playlists');
        back.show(); back.onClick(handler);
        return () => { back.offClick(handler); back.hide(); };
    }, [selectedId]);
    return selectedId ? <PlaylistDetail id={selectedId} onBack={() => openPath('/playlists')} /> : <PlaylistIndex />;
}

function PlaylistIndex() {
    const { data: playlists = [], isLoading, refetch, isFetching } = usePlaylists();
    const [kind, setKind] = useState<Kind>('all');
    const [sort, setSort] = useState<'updated' | 'name' | 'count'>('updated');
    const [view, setView] = useState<'grid' | 'list'>('grid');
    const [showSort, setShowSort] = useState(false);
    const [creating, setCreating] = useState(false);
    const create = useCreatePlaylist();
    const { addToast } = useAppStore();
    const visible = useMemo(() => playlists.filter(p => kind === 'all' || (kind === 'audio' ? p.audio_count > 0 : p.video_count > 0)).sort((a, b) => {
        if (sort === 'name') return a.name.localeCompare(b.name, 'fa');
        if (sort === 'count') return b.item_count - a.item_count || b.updated_at.localeCompare(a.updated_at);
        return b.updated_at.localeCompare(a.updated_at);
    }), [playlists, kind, sort]);
    const sortLabel = sort === 'updated' ? 'تازه‌ترین' : sort === 'name' ? 'نام' : 'تعداد ترک';
    return <div className="mx-auto w-full max-w-7xl p-4 pb-28 sm:p-6 md:pb-8 lg:p-8">
        <header><p className="text-xs font-semibold text-primary-300">🎧 پخش پشت‌سرهم</p><h1 className="mt-1 text-3xl font-bold">پلی‌لیست‌ها</h1><p className="mt-2 text-sm text-dark-400">آهنگ‌ها و ویدیوهایت را هر طور دوست داری بچین.</p></header>
        <div className="mt-5 grid w-full grid-cols-3 rounded-xl border border-white/10 bg-dark-900 p-1">{([['all','همه'],['audio','🎵 صوتی'],['video','🎬 ویدیویی']] as [Kind,string][]).map(([id,label]) => <button key={id} onClick={() => setKind(id)} className={`min-w-0 rounded-lg px-2 py-2 text-sm ${kind === id ? 'bg-primary-500/20 text-primary-200' : 'text-dark-400'}`}>{label}</button>)}</div>
        <button onClick={() => setCreating(true)} className="mt-5 flex min-h-20 w-full items-center gap-4 rounded-2xl border border-dashed border-primary-400/40 bg-primary-500/[.06] p-4 text-right transition hover:bg-primary-500/10"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-primary-500/15 text-primary-200"><Plus className="h-6 w-6"/></span><span><strong className="block text-base">ساخت پلی‌لیست تازه</strong><span className="mt-1 block text-xs text-dark-400">یک صف پخش تازه بساز</span></span></button>
        <section className="mt-6"><div className="mb-4 flex items-center justify-center gap-2"><div className="flex items-center gap-1.5"><div className="relative"><button onClick={() => setShowSort(value => !value)} className="flex h-10 items-center gap-2 rounded-xl border border-white/10 bg-dark-900/80 px-3 text-xs text-dark-200"><ArrowDownUp className="h-4 w-4 text-primary-300"/><span>{sortLabel}</span><ChevronDown className="h-3.5 w-3.5"/></button>{showSort && <div className="absolute left-0 top-full z-40 mt-2 w-40 rounded-2xl border border-white/10 bg-dark-900 p-1.5 shadow-2xl">{([['updated','تازه‌ترین'],['name','نام'],['count','تعداد ترک']] as const).map(([value,label]) => <button key={value} onClick={() => { setSort(value); setShowSort(false); }} className={`block w-full rounded-xl px-3 py-2 text-right text-xs ${sort === value ? 'bg-primary-500/15 text-primary-200' : 'text-dark-300 hover:bg-white/[.05]'}`}>{label}</button>)}</div>}</div><button title="تازه‌سازی" aria-label="تازه‌سازی" onClick={() => void refetch()} className="btn-icon h-10 w-10"><RefreshCw className={`h-4 w-4 ${isFetching ? 'animate-spin' : ''}`}/></button><div className="flex rounded-xl border border-white/10 bg-dark-900/80 p-1"><button aria-label="نمای کارتی" onClick={() => setView('grid')} className={`rounded-lg p-1.5 ${view === 'grid' ? 'bg-primary-500/20 text-primary-200' : 'text-dark-400'}`}><LayoutGrid className="h-4 w-4"/></button><button aria-label="نمای لیستی" onClick={() => setView('list')} className={`rounded-lg p-1.5 ${view === 'list' ? 'bg-primary-500/20 text-primary-200' : 'text-dark-400'}`}><List className="h-4 w-4"/></button></div></div></div>{isLoading ? <div className="h-36 animate-pulse rounded-2xl bg-dark-800"/> : visible.length ? <div className={view === 'grid' ? 'grid gap-4 sm:grid-cols-2 xl:grid-cols-3' : 'flex flex-col gap-2'}>{visible.map(p => <PlaylistCard key={p.id} playlist={p} view={view} />)}</div> : <div className="rounded-2xl border border-dashed border-white/10 py-12 text-center text-dark-400">هنوز پلی‌لیستی اینجا نیست.</div>}</section>
        {creating && <PlaylistEditor title="پلی‌لیست تازه" onClose={() => setCreating(false)} onSave={async (name, description) => { const p = await create.mutateAsync({ name, description }); setCreating(false); addToast('پلی‌لیست ساخته شد 🎶'); openPath(`/playlist/${p.id}`); }} />}
    </div>;
}

function PlaylistCard({ playlist, view }: { playlist: PlaylistSummary; view: 'grid' | 'list' }) {
    const grid = view === 'grid';
    return <button dir="ltr" onClick={() => openPath(`/playlist/${playlist.id}`)} className={`group flex gap-4 overflow-hidden rounded-2xl border border-white/[.07] bg-dark-900/65 text-left transition hover:border-primary-500/30 ${grid ? 'flex-col items-stretch p-3' : 'min-h-24 items-center p-3'}`}><Collage urls={playlist.cover_urls} customUrl={playlist.cover_file_id ? playlist.cover_url : null} large={grid}/><span dir="rtl" className="min-w-0 flex-1 text-right"><strong dir="auto" className={`block truncate ${grid ? 'text-lg' : 'text-base'}`}>{playlist.name}</strong><span className="mt-2 flex flex-wrap gap-1.5"><span className="rounded-full bg-white/[.05] px-2 py-1 text-[11px] text-dark-300">🎵 {playlist.item_count.toLocaleString('fa-IR')} ترک</span><span className="rounded-full bg-white/[.05] px-2 py-1 text-[11px] text-dark-300">⏱️ {formatDuration(playlist.total_duration) || 'نامشخص'}</span></span><span className={`mt-2 gap-1 ${grid ? 'grid' : 'hidden sm:grid'}`}>{playlist.preview_names?.length ? playlist.preview_names.slice(0,2).map((name,index) => <span key={index} dir="auto" className="truncate text-[11px] text-dark-500">♪ {name}</span>) : <span className="text-[11px] text-dark-500">هنوز ترکی اضافه نشده</span>}</span></span></button>;
}

function CoverTile({ src, className = '' }: { src: string; className?: string }) {
    const [failed, setFailed] = useState(false);
    useEffect(() => setFailed(false), [src]);
    return failed ? <span className={`${className} flex items-center justify-center bg-gradient-to-br from-primary-500/25 via-dark-800 to-pink-500/20 text-2xl`}>🎶</span> : <img loading="lazy" decoding="async" src={src} className={className} alt="" onError={() => setFailed(true)}/>;
}

function Collage({ urls, customUrl, large = false }: { urls: string[]; customUrl?: string | null; large?: boolean }) {
    const token = localStorage.getItem('access_token');
    const auth = (url: string) => `${url}${url.includes('?') ? '&' : '?'}token=${encodeURIComponent(token || '')}`;
    return <span className={`grid shrink-0 grid-cols-2 overflow-hidden rounded-xl bg-gradient-to-br from-primary-500/30 to-pink-500/20 shadow-lg shadow-black/20 ${large ? 'aspect-square w-full' : 'h-16 w-16'}`}>{customUrl ? <CoverTile src={auth(customUrl)} className="col-span-2 h-full w-full object-cover"/> : urls.length ? urls.slice(0,4).map((url,i) => <CoverTile key={i} src={auth(url)} className="h-full w-full object-cover"/>) : <span className="col-span-2 flex items-center justify-center bg-gradient-to-br from-primary-500/20 via-dark-800 to-pink-500/20 text-3xl">🎶</span>}</span>;
}

function CoverPreview({ playlist }: { playlist: Playlist }) {
    const token = localStorage.getItem('access_token');
    const [failed, setFailed] = useState(false);
    useEffect(() => setFailed(false), [playlist.cover_url]);
    if (!playlist.cover_file_id || !playlist.cover_url || failed) return <Collage urls={playlist.cover_urls}/>;
    return <span className="block h-52 w-52 shrink-0 overflow-hidden rounded-2xl bg-dark-800 shadow-2xl shadow-black/40"><img loading="eager" decoding="async" src={`${playlist.cover_url}${playlist.cover_url.includes('?')?'&':'?'}token=${encodeURIComponent(token || '')}`} className="h-full w-full object-cover" alt="کاور پلی‌لیست" onError={() => setFailed(true)}/></span>;
}

function PlaylistDetail({ id, onBack }: { id: number; onBack: () => void }) {
    const { data: playlist, isLoading } = usePlaylist(id);
    const reorder = useReorderPlaylist(); const shuffle = useShufflePlaylist(); const remove = useRemovePlaylistItem(); const del = useDeletePlaylist();
    const { startQueue, addToast } = useAppStore();
    const [adding, setAdding] = useState(false); const [editing, setEditing] = useState(false); const [coverPicker, setCoverPicker] = useState(false); const [menu, setMenu] = useState(false); const [managing, setManaging] = useState(false); const [selected, setSelected] = useState<Set<number>>(new Set()); const [activeItem, setActiveItem] = useState<number | null>(null); const [orderedItems, setOrderedItems] = useState<PlaylistItem[]>([]);
    useEffect(() => { if (playlist) setOrderedItems(playlist.items); }, [playlist]);
    const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 4 } }), useSensor(TouchSensor, { activationConstraint: { delay: 80, tolerance: 5 } }));
    if (isLoading || !playlist) return <div className="m-6 h-52 animate-pulse rounded-3xl bg-dark-800"/>;
    const play = (index = 0) => startQueue(orderedItems.map(x => x.file), index);
    const toggleSelected = (itemId: number) => setSelected(previous => { const next = new Set(previous); next.has(itemId) ? next.delete(itemId) : next.add(itemId); return next; });
    const selectAll = () => setSelected(selected.size === orderedItems.length ? new Set() : new Set(orderedItems.map(item => item.id)));
    const playSelected = () => { const files = orderedItems.filter(item => selected.has(item.id)).map(item => item.file); if (files.length) startQueue(files, 0); };
    const deleteSelected = async () => { try { await Promise.all([...selected].map(itemId => remove.mutateAsync({ id, itemId }))); setSelected(new Set()); setManaging(false); } catch { addToast('حذف بعضی ترک‌ها انجام نشد', 'error'); } };
    const dragEnd = async ({ active, over }: DragEndEvent) => { setActiveItem(null); if (!over || active.id === over.id) return; const old = orderedItems.findIndex(x => x.id === active.id); const next = orderedItems.findIndex(x => x.id === over.id); const nextItems = arrayMove(orderedItems, old, next); setOrderedItems(nextItems); try { await reorder.mutateAsync({ id, itemIds: nextItems.map(x => x.id) }); } catch { setOrderedItems(playlist.items); addToast('ذخیرهٔ ترتیب انجام نشد', 'error'); } };
    const requestDelete = () => { const run = async () => { await del.mutateAsync(id); addToast('پلی‌لیست حذف شد'); onBack(); }; const message=`پلی‌لیست «${playlist.name}» حذف شود؟ فایل‌ها باقی می‌مانند.`; telegram()?.showConfirm ? telegram().showConfirm(message, (yes: boolean) => yes && void run()) : confirm(message) && void run(); };
    return <div className="mx-auto w-full max-w-5xl p-4 pb-28 sm:p-6 md:pb-8 lg:p-8">
        {managing ? <div className="mb-4 flex items-center gap-3 border-b border-white/[.06] pb-3"><button className="btn-icon" onClick={() => { setManaging(false); setSelected(new Set()); }} aria-label="بازگشت"><X className="h-5 w-5"/></button><strong className="text-lg">{selected.size.toLocaleString('fa-IR')} انتخاب‌شده</strong><button className="mr-auto rounded-full border border-white/10 px-3 py-1.5 text-xs text-dark-200" onClick={selectAll}>{selected.size === orderedItems.length ? 'لغو انتخاب همه' : 'انتخاب همه'}</button></div> : <><button className="btn-icon mb-4 md:hidden" onClick={onBack} title="بازگشت" aria-label="بازگشت به پلی‌لیست‌ها"><ChevronRight className="h-5 w-5"/></button><header className="relative flex flex-col items-center gap-5 p-2 text-center"><button className="group relative shrink-0 overflow-hidden rounded-2xl" title="تغییر عکس پلی‌لیست" onClick={() => setCoverPicker(true)}><CoverPreview playlist={playlist}/><span className="absolute inset-x-0 bottom-0 flex items-center justify-center gap-1 bg-black/65 py-2 text-xs text-white opacity-90 backdrop-blur"><Image className="h-3.5 w-3.5"/> تغییر کاور</span></button><div className="min-w-0 w-full"><div className="flex items-center justify-center gap-2"><h1 dir="auto" className="truncate text-3xl font-black">{playlist.name}</h1><button className="btn-icon" onClick={() => setEditing(true)} title="ویرایش نام"><Pencil className="h-4 w-4"/></button></div>{playlist.description && <p dir="auto" className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-dark-300">{playlist.description}</p>}<div className="mx-auto mt-4 flex max-w-sm flex-col items-center gap-1.5 text-sm"><span className="font-medium text-dark-200">🎵 {playlist.item_count.toLocaleString('fa-IR')} ترک در این پلی‌لیست</span><span className="text-dark-400">⏱️ زمان کل پخش: {formatDuration(playlist.total_duration) || 'نامشخص'}</span></div><div className="mx-auto mt-5 grid w-full max-w-xl grid-cols-2 gap-2"><button disabled={!orderedItems.length} className="btn-primary flex h-11 items-center justify-center gap-2 rounded-full !border-0 outline-none ring-0" title="پخش همه" onClick={() => play()}><Play className="h-4 w-4"/> پخش همه</button><button disabled={orderedItems.length < 2} className="btn-secondary flex h-11 items-center justify-center gap-2 rounded-full !border-0 outline-none ring-0" title="شافل" onClick={async () => { await shuffle.mutateAsync(id); }}><Shuffle className="h-4 w-4"/> شافل همه</button></div><button className="btn-secondary mx-auto mt-3 flex h-11 w-full max-w-xl items-center justify-center gap-2 rounded-full text-sm" onClick={() => setAdding(true)}><Plus className="h-4 w-4"/> افزودن فایل</button></div><div className="absolute left-4 top-4"><button className="btn-icon" onClick={() => setMenu(true)} aria-label="گزینه‌های پلی‌لیست"><MoreVertical className="h-5 w-5"/></button></div></header></>}
        <DndContext sensors={sensors} collisionDetection={closestCenter} onDragStart={({ active }) => setActiveItem(Number(active.id))} onDragCancel={() => setActiveItem(null)} onDragEnd={dragEnd}><SortableContext items={orderedItems.map(x => x.id)} strategy={verticalListSortingStrategy}><div className="mt-5">{orderedItems.map((item,index) => <TrackRow key={item.id} item={item} manage={managing} selected={selected.has(item.id)} onToggle={() => toggleSelected(item.id)} onPlay={() => play(index)}/>)}</div></SortableContext><DragOverlay>{activeItem ? <div className="rounded-xl border border-primary-500/40 bg-dark-800 px-4 py-3 shadow-2xl">{orderedItems.find(item => item.id === activeItem)?.file.file_name}</div> : null}</DragOverlay></DndContext>
        {!orderedItems.length && <button onClick={() => setAdding(true)} className="mt-5 w-full rounded-2xl border border-dashed border-white/10 py-14 text-dark-300">این پلی‌لیست هنوز خالیه! <span className="mt-2 block text-primary-300">➕ افزودن اولین آهنگ یا ویدیو</span></button>}
        {managing && <div className="fixed inset-x-0 bottom-[calc(4.5rem+env(safe-area-inset-bottom))] z-[110] mx-auto flex max-w-3xl items-center justify-around border-t border-white/10 bg-dark-900/95 px-2 py-3 shadow-2xl backdrop-blur-xl"><button className="flex flex-col items-center gap-1 text-xs text-dark-200" onClick={() => setAdding(true)}><Plus className="h-5 w-5"/> افزودن به</button><button className="flex flex-col items-center gap-1 text-xs text-dark-200" onClick={playSelected}><Play className="h-5 w-5"/> پخش بعدی</button><button className="flex flex-col items-center gap-1 text-xs text-dark-200" onClick={() => { navigator.clipboard?.writeText(window.location.href); addToast('پیوند پلی‌لیست کپی شد'); }}><Share2 className="h-5 w-5"/> اشتراک</button><button disabled={!selected.size} className="flex flex-col items-center gap-1 text-xs text-red-300 disabled:opacity-30" onClick={() => void deleteSelected()}><Trash2 className="h-5 w-5"/> حذف از پلی‌لیست</button></div>}
        {menu && <div className="fixed inset-0 z-[140] flex items-end bg-black/60 backdrop-blur-sm" onClick={() => setMenu(false)}><div className="w-full rounded-t-3xl border-t border-white/10 bg-dark-900 p-4 pb-[calc(1rem+env(safe-area-inset-bottom))]" onClick={event => event.stopPropagation()}><div className="mx-auto mb-4 h-1 w-12 rounded-full bg-white/20"/><button className="context-menu-item w-full py-3" onClick={() => { setAdding(true); setMenu(false); }}><Plus className="h-5 w-5"/> افزودن فایل</button><button className="context-menu-item w-full py-3" onClick={() => { setManaging(true); setMenu(false); }}><Check className="h-5 w-5"/> مدیریت</button><button className="context-menu-item w-full py-3 text-red-300" onClick={() => { setMenu(false); requestDelete(); }}><Trash2 className="h-5 w-5"/> حذف پلی‌لیست</button></div></div>}
        {adding && <BulkAdd playlist={playlist} onClose={() => setAdding(false)}/>} {editing && <EditPlaylist playlist={playlist} close={() => setEditing(false)}/>} {coverPicker && <CoverPicker playlist={playlist} onClose={() => setCoverPicker(false)}/>} 
    </div>;
}

function TrackRow({ item, manage, selected, onToggle, onPlay }: { item: PlaylistItem; manage: boolean; selected: boolean; onToggle: () => void; onPlay: () => void }) {
    const sortable = useSortable({ id: item.id }); const token = localStorage.getItem('access_token');
    const [thumbnailFailed, setThumbnailFailed] = useState(false);
    const [menu, setMenu] = useState(false); const [saving, setSaving] = useState(false); const { addToast } = useAppStore();
    const thumbnail = item.file.thumbnail_url ? `${item.file.thumbnail_url}${item.file.thumbnail_url.includes('?') ? '&' : '?'}token=${encodeURIComponent(token || '')}` : null;
    const title = item.file.file_name.replace(/\.[^/.]+$/, '');
    return <div dir="ltr" ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.isDragging ? undefined : sortable.transition }} onClick={manage ? onToggle : onPlay} className={`group flex min-h-[72px] cursor-pointer items-center gap-3 border-b border-white/[.06] px-1 py-3 transition-colors hover:bg-white/[.035] ${selected ? 'bg-primary-500/[.08]' : ''} ${sortable.isDragging ? 'z-10 opacity-60 shadow-xl' : ''}`}>
        {manage ? <span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full border ${selected ? 'border-primary-400 bg-primary-500 text-white' : 'border-white/25 text-transparent'}`}><Check className="h-4 w-4"/></span> : <div className="relative flex shrink-0 items-center"><button {...sortable.attributes} {...sortable.listeners} onClick={event => event.stopPropagation()} className="flex h-11 w-8 touch-none items-center justify-center text-dark-500 hover:text-dark-200" title="برای جابه‌جایی بکش"><GripVertical className="h-5 w-5"/></button><button className="btn-icon h-9 w-9" aria-label="گزینه‌های ترک" onClick={event => { event.stopPropagation(); setMenu(value => !value); }}><MoreVertical className="h-4 w-4"/></button>{menu && <div className="absolute left-0 top-full z-40 mt-1 w-56 rounded-2xl border border-white/10 bg-dark-900 p-1.5 shadow-2xl" onClick={event => event.stopPropagation()}><button disabled={saving} className="context-menu-item w-full whitespace-nowrap disabled:opacity-50" onClick={async () => { setSaving(true); try { await saveFileOffline(item.file); addToast('برای پخش آفلاین ذخیره شد 📥'); setMenu(false); } catch (error) { addToast(error instanceof Error ? error.message : 'ذخیره آفلاین انجام نشد', 'error'); } finally { setSaving(false); } }}><DownloadCloud className="h-4 w-4"/> {saving ? 'در حال ذخیره…' : 'ذخیره برای پخش آفلاین'}</button></div>}</div>}
        <span className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-gradient-to-br from-primary-500/20 via-dark-800 to-pink-500/15 text-primary-200">{thumbnail && !thumbnailFailed ? <img loading="lazy" decoding="async" src={thumbnail} alt="" className="h-full w-full object-cover" onError={() => setThumbnailFailed(true)}/> : item.file.file_type === 'video' ? <Film className="h-5 w-5"/> : <Music className="h-5 w-5"/>}</span>
        <span dir="auto" className="min-w-0 flex-1 text-right"><strong className="block truncate text-sm font-semibold text-white">{title}</strong><span className="mt-1 block truncate text-xs text-dark-500">{item.file.file_type === 'video' ? 'ویدیو' : 'صوت'} {item.file.duration ? `· ${formatDuration(item.file.duration)}` : ''}</span></span>
        {manage && <button {...sortable.attributes} {...sortable.listeners} onClick={event => event.stopPropagation()} className="flex h-11 w-8 shrink-0 touch-none items-center justify-center text-dark-500" title="جابه‌جایی"><GripVertical className="h-5 w-5"/></button>}
    </div>;
}

function BulkAdd({ playlist, onClose }: { playlist: Playlist; onClose: () => void }) {
    const [query,setQuery] = useState(''); const [folder,setFolder] = useState<number|null>(null); const [kind,setKind] = useState<Kind>('all'); const [selected,setSelected] = useState<Set<number>>(new Set());
    const { data } = useFiles(folder, kind === 'all' ? 'audio,video' : kind, query || undefined, 1, 'name:asc'); const { data: folders=[] } = useFolders(null); const add = useAddPlaylistItems();
    const existing = useMemo(() => new Set(playlist.items.map(x => x.file.id)), [playlist]);
    const submit = async () => { const ids=[...selected]; const duplicates=ids.filter(fileId => existing.has(fileId)); const run=async(allowDuplicates:boolean)=>{await add.mutateAsync({id:playlist.id,fileIds:ids,allowDuplicates});onClose()}; if (!duplicates.length) return run(false); const message='بعضی فایل‌ها قبلاً اضافه شده‌اند؛ دوباره هم اضافه شوند؟'; if(telegram()?.showConfirm) telegram().showConfirm(message,(yes:boolean)=>void run(yes)); else void run(confirm(message)); };
    const visibleFiles = data?.files || [];
    const allVisibleSelected = visibleFiles.length > 0 && visibleFiles.every(file => selected.has(file.id));
    const toggleAll = () => setSelected(previous => { const next = new Set(previous); visibleFiles.forEach(file => allVisibleSelected ? next.delete(file.id) : next.add(file.id)); return next; });
    return <div className="fixed inset-0 z-[150] flex items-end bg-black/70 backdrop-blur-sm" onClick={onClose}><div className="mx-auto flex max-h-[88vh] w-full max-w-2xl flex-col rounded-t-3xl border border-white/10 bg-dark-900 p-4 pb-[calc(1rem+env(safe-area-inset-bottom))]" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-3 h-1 w-12 rounded-full bg-white/20"/><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">افزودن فایل‌ها</h2><p className="mt-1 text-xs text-dark-500">فایل‌های صوتی و ویدیویی را انتخاب کن.</p></div><button className="btn-icon" onClick={onClose}><X className="h-5 w-5"/></button></div><div className="relative mt-4"><Search className="absolute right-3 top-3 h-4 w-4 text-dark-500"/><input className="input w-full pr-9" placeholder="جست‌وجوی آهنگ یا ویدیو…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="mt-3 grid grid-cols-3 rounded-xl border border-white/[.07] bg-dark-800/70 p-1">{([['all','همه'],['audio','🎵 آهنگ'],['video','🎬 ویدیو']] as [Kind,string][]).map(([value,label]) => <button key={value} onClick={() => setKind(value)} className={`rounded-lg px-2 py-2 text-xs ${kind === value ? 'bg-primary-500/20 text-primary-200' : 'text-dark-400'}`}>{label}</button>)}</div><CustomSelect className="mt-3" label="کشوی فایل‌ها" value={folder ?? 0} onChange={value => setFolder(value === 0 ? null : Number(value))} options={[{ value: 0, label: 'همه کشوها' }, ...folders.map(item => ({ value: item.id, label: item.name }))]}/><div className="mt-3 flex items-center justify-between border-b border-white/[.06] pb-2"><span className="text-xs text-dark-400">{selected.size.toLocaleString('fa-IR')} مورد انتخاب شده</span><button className="rounded-lg px-2 py-1 text-xs text-primary-300 hover:bg-primary-500/10" onClick={toggleAll}>{allVisibleSelected ? 'لغو انتخاب همه' : 'انتخاب همه'}</button></div><div className="min-h-0 flex-1 space-y-1 overflow-y-auto">{visibleFiles.map(file=><button key={file.id} onClick={()=>setSelected(prev=>{const n=new Set(prev);n.has(file.id)?n.delete(file.id):n.add(file.id);return n})} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-right ${selected.has(file.id)?'border-primary-500/40 bg-primary-500/10':'border-transparent hover:bg-white/[.04]'}`}><span className={`h-5 w-5 rounded border ${selected.has(file.id)?'border-primary-400 bg-primary-500':'border-white/20'}`}/><span>{file.file_type==='video'?<Film className="h-4 w-4"/>:<Music className="h-4 w-4"/>}</span><span className="min-w-0 flex-1 truncate text-sm">{file.file_name}</span>{existing.has(file.id)&&<span className="text-[10px] text-amber-300">قبلاً افزوده شده</span>}</button>)}</div><button disabled={!selected.size||add.isPending} className="btn-primary mt-4" onClick={submit}>افزودن ({selected.size.toLocaleString('fa-IR')})</button></div></div>;
}

function CoverPicker({ playlist, onClose }: { playlist: Playlist; onClose: () => void }) {
    const { data } = useFiles(null, 'image', undefined, 1, 'created:desc', false, true);
    const update = useUpdatePlaylist(); const upload = useUploadFile();
    const uploadCover = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file || !file.type.startsWith('image/')) return; const uploaded = await upload.mutateAsync({ file, folderId: null }); await update.mutateAsync({ id: playlist.id, cover_file_id: uploaded.id }); onClose(); };
    return <div className="fixed inset-0 z-[160] flex items-end bg-black/70 backdrop-blur-sm" onClick={onClose}><div className="mx-auto max-h-[80vh] w-full max-w-2xl rounded-t-3xl border border-white/10 bg-dark-900 p-4" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-lg font-bold">انتخاب عکس پلی‌لیست</h2><div className="flex items-center gap-2"><label className="btn-secondary flex h-9 cursor-pointer items-center gap-1.5 px-3 text-xs"><Upload className="h-3.5 w-3.5"/> آپلود عکس<input type="file" accept="image/*" className="hidden" onChange={uploadCover} /></label><button className="btn-icon" onClick={onClose}><X className="h-5 w-5"/></button></div></div><div className="mt-4 grid max-h-[60vh] grid-cols-3 gap-3 overflow-y-auto sm:grid-cols-5">{(data?.files || []).map(file => <button key={file.id} disabled={update.isPending || upload.isPending} onClick={async () => { await update.mutateAsync({ id: playlist.id, cover_file_id: file.id }); onClose(); }} className={`overflow-hidden rounded-xl border ${playlist.cover_file_id === file.id ? 'border-primary-400 ring-2 ring-primary-500/30' : 'border-white/10'}`}><img loading="lazy" decoding="async" src={`${file.stream_url}?token=${encodeURIComponent(localStorage.getItem('access_token') || '')}`} className="aspect-square w-full object-cover"/><span className="block truncate p-1 text-[10px]">{file.file_name}</span></button>)}</div>{!data?.files.length && <p className="py-10 text-center text-sm text-dark-400">هنوز عکس تصویری در کمد نداری.</p>}</div></div>;
}

function EditPlaylist({ playlist, close }: { playlist: Playlist; close: () => void }) { const update=useUpdatePlaylist(); return <PlaylistEditor title="ویرایش پلی‌لیست" initialName={playlist.name} initialDescription={playlist.description||''} onClose={close} onSave={async(name,description)=>{await update.mutateAsync({id:playlist.id,name,description});close()}}/>; }
function PlaylistEditor({ title, initialName='', initialDescription='', onClose, onSave }: { title:string; initialName?:string; initialDescription?:string; onClose:()=>void; onSave:(name:string,description:string)=>Promise<void> }) {
    const [name,setName]=useState(initialName); const [description,setDescription]=useState(initialDescription); const [saving,setSaving]=useState(false);
    return <div className="fixed inset-0 z-[170] flex items-center justify-center bg-black/70 p-4" onClick={onClose}><form className="w-full max-w-md rounded-2xl border border-white/10 bg-dark-900 p-5" onClick={e=>e.stopPropagation()} onSubmit={async e=>{e.preventDefault();if(!name.trim())return;setSaving(true);try{await onSave(name.trim(),description.trim())}finally{setSaving(false)}}}>
        <div className="flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><button type="button" className="btn-icon" onClick={onClose}><X className="h-5 w-5"/></button></div><input autoFocus maxLength={255} className="input mt-4 w-full" placeholder="نام پلی‌لیست" value={name} onChange={e=>setName(e.target.value)}/><textarea maxLength={1024} className="input mt-3 min-h-24 w-full" placeholder="توضیحات (اختیاری)" value={description} onChange={e=>setDescription(e.target.value)}/><button disabled={saving||!name.trim()} className="btn-primary mt-4 flex w-full items-center justify-center gap-2"><Save className="h-4 w-4"/>{saving?'در حال ذخیره…':'ذخیره'}</button>
    </form></div>;
}
