import { useEffect, useMemo, useRef, useState } from 'react';
import { DndContext, DragEndEvent, DragOverlay, PointerSensor, TouchSensor, closestCenter, useSensor, useSensors } from '@dnd-kit/core';
import { SortableContext, arrayMove, rectSortingStrategy, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { ArrowDownUp, Check, ChevronDown, ChevronRight, DownloadCloud, Film, GripVertical, Grid3X3, Image, LayoutGrid, List, MoreVertical, Music, Pencil, Play, Plus, RefreshCw, Save, Search, Share2, Shuffle, Trash2, Upload, X } from 'lucide-react';
import { api, formatDuration, Playlist, PlaylistItem, PlaylistSummary, useAddPlaylistItems, useCreatePlaylist, useDeletePlaylist, useFiles, useFolders, usePlaylist, usePlaylists, useRemovePlaylistItem, useReorderPlaylist, useReorderPlaylistCatalog, useShufflePlaylist, useUpdatePlaylist, useUploadFile } from '../lib/api';
import { useAppStore } from '../lib/store';
import CustomSelect from './CustomSelect';
import { saveFileOffline, savePlaylistOffline } from '../lib/offline';

type Kind = 'all' | 'audio' | 'video';
const telegram = () => (window as Window & { Telegram?: { WebApp?: any } }).Telegram?.WebApp;
const openPath = (path: string) => { if (location.pathname !== path) history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); };

export default function PlaylistBrowser() {
    const [path, setPath] = useState(location.pathname);
    const selectedId = Number(path.match(/^\/playlist\/(\d+)/)?.[1]) || null;
    useEffect(() => { const sync = () => setPath(location.pathname); addEventListener('popstate', sync); return () => removeEventListener('popstate', sync); }, []);
    useEffect(() => {
        const back = telegram()?.BackButton;
        if (!back || !selectedId) return;
        const handler = () => openPath('/playlists');
        back.show(); back.onClick(handler);
        return () => { back.offClick(handler); back.hide(); };
    }, [selectedId]);
    return selectedId ? <PlaylistDetail id={selectedId} onBack={() => openPath('/playlists')} /> : <PlaylistIndex />;
}

function PlaylistIndex() {
    const readOnlyWorkspace = Boolean(localStorage.getItem('komod-active-workspace')) && localStorage.getItem('komod-active-workspace-permission') === 'read';
    const { data: playlists = [], isLoading, refetch, isFetching } = usePlaylists();
    const [kind, setKind] = useState<Kind>('all');
    const [sort, setSort] = useState<'manual' | 'updated' | 'name' | 'count'>('manual');
    const [view, setView] = useState<'grid' | 'dense' | 'list'>('list');
    const [showSort, setShowSort] = useState(false);
    const [creating, setCreating] = useState(false);
    const [editing, setEditing] = useState<PlaylistSummary | null>(null);
    const [menuPlaylist, setMenuPlaylist] = useState<PlaylistSummary | null>(null);
    const create = useCreatePlaylist();
    const update = useUpdatePlaylist();
    const removePlaylist = useDeletePlaylist();
    const reorderCatalog = useReorderPlaylistCatalog();
    const { addToast } = useAppStore();
    const visible = useMemo(() => playlists.filter(p => kind === 'all' || (kind === 'audio' ? p.audio_count > 0 : p.video_count > 0)).sort((a, b) => {
        if (sort === 'manual') return (a.position || 0) - (b.position || 0);
        if (sort === 'name') return a.name.localeCompare(b.name, 'fa');
        if (sort === 'count') return b.item_count - a.item_count || b.updated_at.localeCompare(a.updated_at);
        return b.updated_at.localeCompare(a.updated_at);
    }), [playlists, kind, sort]);
    const sortLabel = sort === 'manual' ? 'ترتیب دستی' : sort === 'updated' ? 'تازه‌ترین' : sort === 'name' ? 'نام' : 'تعداد ترک';
    const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(TouchSensor, { activationConstraint: { delay: 180, tolerance: 8 } }));
    const reorderCards = async ({ active, over }: DragEndEvent) => {
        if (readOnlyWorkspace || sort !== 'manual' || kind !== 'all' || !over || active.id === over.id) return;
        const oldIndex = visible.findIndex(item => item.id === active.id);
        const newIndex = visible.findIndex(item => item.id === over.id);
        const ordered = arrayMove(visible, oldIndex, newIndex);
        try { await reorderCatalog.mutateAsync(ordered.map(item => item.id)); }
        catch { addToast('ذخیره ترتیب پلی‌لیست‌ها انجام نشد.', 'error'); }
    };
    const deleteFromMenu = async (playlist: PlaylistSummary) => {
        const run = async () => { await removePlaylist.mutateAsync(playlist.id); setMenuPlaylist(null); addToast('پلی‌لیست حذف شد'); };
        const message = `پلی‌لیست «${playlist.name}» حذف شود؟ فایل‌ها باقی می‌مانند.`;
        telegram()?.showConfirm ? telegram().showConfirm(message, (yes: boolean) => yes && void run()) : confirm(message) && void run();
    };
    const downloadFromMenu = async (playlist: PlaylistSummary) => {
        setMenuPlaylist(null);
        try { const { data } = await api.get<Playlist>(`/playlists/${playlist.id}`); void savePlaylistOffline(data); addToast('دانلود پلی‌لیست شروع شد 📥'); }
        catch { addToast('شروع دانلود پلی‌لیست انجام نشد.', 'error'); }
    };
    return <div className="mx-auto w-full max-w-7xl p-4 pb-28 sm:p-6 md:pb-8 lg:p-8">
        <header><p className="text-xs font-semibold text-primary-300">🎧 پخش پشت‌سرهم</p><h1 className="mt-1 text-3xl font-bold">پلی‌لیست‌ها</h1><p className="mt-2 text-sm text-dark-400">آهنگ‌ها و ویدیوهایت را هر طور دوست داری بچین.</p></header>
        <div className="mt-5 grid w-full grid-cols-3 rounded-xl border border-white/10 bg-dark-900 p-1">{([['all','همه'],['audio','🎵 صدا'],['video','🎬 ویدیو']] as [Kind,string][]).map(([id,label]) => <button key={id} onClick={() => setKind(id)} className={`min-w-0 rounded-lg px-2 py-2 text-sm ${kind === id ? 'bg-primary-500/20 text-primary-200' : 'text-dark-400'}`}>{label}</button>)}</div>
        {!readOnlyWorkspace && <button onClick={() => setCreating(true)} className="mt-5 flex min-h-20 w-full items-center gap-4 rounded-2xl border border-dashed border-primary-400/40 bg-primary-500/[.06] p-4 text-right transition hover:bg-primary-500/10"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-primary-500/15 text-primary-200"><Plus className="h-6 w-6"/></span><span><strong className="block text-base">ساخت پلی‌لیست تازه</strong><span className="mt-1 block text-xs text-dark-400">یک صف پخش تازه بساز</span></span></button>}
        <section className="mt-6">
            <div className="relative mb-4 flex w-full items-center gap-2 rounded-2xl border border-white/10 bg-dark-900/65 p-1.5">
                <div className="relative min-w-0 flex-1">
                    <button onClick={() => setShowSort(value => !value)} className="flex h-10 w-full items-center justify-center gap-2 rounded-xl px-3 text-xs text-dark-200 hover:bg-white/[.05]"><ArrowDownUp className="h-4 w-4 text-primary-300"/><span>{sortLabel}</span><ChevronDown className="h-3.5 w-3.5"/></button>
                    {showSort && <div className="absolute inset-x-0 top-full z-40 mt-2 rounded-2xl border border-white/10 bg-dark-900 p-1.5 shadow-2xl">{([['manual','ترتیب دستی'],['updated','تازه‌ترین'],['name','نام'],['count','تعداد ترک']] as const).map(([value,label]) => <button key={value} onClick={() => { setSort(value); setShowSort(false); }} className={`block w-full rounded-xl px-3 py-2 text-right text-xs ${sort === value ? 'bg-primary-500/15 text-primary-200' : 'text-dark-300 hover:bg-white/[.05]'}`}>{label}</button>)}</div>}
                </div>
                <button title="تازه‌سازی" aria-label="تازه‌سازی" onClick={() => void refetch()} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-dark-400 hover:bg-white/[.05] hover:text-white"><RefreshCw className={`h-4 w-4 ${isFetching ? 'animate-spin' : ''}`}/></button>
                <div className="flex h-10 shrink-0 rounded-xl bg-dark-950/60 p-1"><button aria-label="نمای کارتی" onClick={() => setView('grid')} className={`rounded-lg px-2 ${view === 'grid' ? 'bg-primary-500/20 text-primary-200' : 'text-dark-400'}`}><LayoutGrid className="h-4 w-4"/></button><button aria-label="نمای کاشی کوچک" onClick={() => setView('dense')} className={`rounded-lg px-2 ${view === 'dense' ? 'bg-primary-500/20 text-primary-200' : 'text-dark-400'}`}><Grid3X3 className="h-4 w-4"/></button><button aria-label="نمای لیستی" onClick={() => setView('list')} className={`rounded-lg px-2 ${view === 'list' ? 'bg-primary-500/20 text-primary-200' : 'text-dark-400'}`}><List className="h-4 w-4"/></button></div>
            </div>
            {isLoading ? <div className="h-36 animate-pulse rounded-2xl bg-dark-800"/> : visible.length ? <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={reorderCards}><SortableContext items={visible.map(item => item.id)} strategy={rectSortingStrategy}><div className={view === 'grid' ? 'grid gap-4 sm:grid-cols-2 xl:grid-cols-3' : view === 'dense' ? 'grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5' : 'flex flex-col gap-2'}>{visible.map(p => <PlaylistCard key={p.id} playlist={p} view={view} manual={!readOnlyWorkspace && sort === 'manual' && kind === 'all'} onLongPress={() => setMenuPlaylist(p)} />)}</div></SortableContext></DndContext> : <div className="rounded-2xl border border-dashed border-white/10 py-12 text-center text-dark-400">هنوز پلی‌لیستی اینجا نیست.</div>}
        </section>
        {creating && <PlaylistEditor title="پلی‌لیست تازه" onClose={() => setCreating(false)} onSave={async (name, description) => { const p = await create.mutateAsync({ name, description }); setCreating(false); addToast('پلی‌لیست ساخته شد 🎶'); openPath(`/playlist/${p.id}`); }} />}
        {editing && <PlaylistEditor title="ویرایش پلی‌لیست" initialName={editing.name} initialDescription={editing.description || ''} onClose={() => setEditing(null)} onSave={async (name, description) => { await update.mutateAsync({ id: editing.id, name, description }); setEditing(null); }} />}
        {menuPlaylist && <div className="fixed inset-0 z-[160] flex items-end bg-black/65 backdrop-blur-sm" onClick={() => setMenuPlaylist(null)}><div className="w-full rounded-t-3xl border-t border-white/10 bg-dark-900 p-4 pb-[calc(1rem+env(safe-area-inset-bottom))]" onClick={event => event.stopPropagation()}><div className="mx-auto mb-4 h-1 w-12 rounded-full bg-white/20"/><h2 dir="auto" className="mb-3 truncate px-2 font-bold">{menuPlaylist.name}</h2>{!readOnlyWorkspace && <><button className="context-menu-item min-h-14 w-full" onClick={() => { setEditing(menuPlaylist); setMenuPlaylist(null); }}><Pencil className="h-5 w-5"/> ویرایش</button><button className="context-menu-item min-h-14 w-full" onClick={() => openPath(`/playlist/${menuPlaylist.id}?manage=1`)}><Check className="h-5 w-5"/> مدیریت فایل‌ها</button></>}<button className="context-menu-item min-h-14 w-full" onClick={() => void downloadFromMenu(menuPlaylist)}><DownloadCloud className="h-5 w-5"/> دانلود و ذخیره آفلاین</button>{!readOnlyWorkspace && <button className="context-menu-item min-h-14 w-full text-red-300" onClick={() => void deleteFromMenu(menuPlaylist)}><Trash2 className="h-5 w-5"/> حذف پلی‌لیست</button>}</div></div>}
    </div>;
}

function PlaylistCard({ playlist, view, manual, onLongPress }: { playlist: PlaylistSummary; view: 'grid' | 'dense' | 'list'; manual: boolean; onLongPress: () => void }) {
    const grid = view === 'grid';
    const dense = view === 'dense';
    const sortable = useSortable({ id: playlist.id, disabled: !manual });
    const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
    const held = useRef(false);
    const clear = () => { if (timer.current) clearTimeout(timer.current); timer.current = null; };
    const start = () => { held.current = false; timer.current = setTimeout(() => { held.current = true; onLongPress(); }, 550); };
    return <article ref={sortable.setNodeRef} style={{transform:CSS.Transform.toString(sortable.transform),transition:sortable.transition}} dir="ltr" onPointerDown={start} onPointerUp={clear} onPointerCancel={clear} onPointerLeave={clear} onClick={() => { if (held.current) { held.current=false; return; } openPath(`/playlist/${playlist.id}`); }} className={`group relative flex cursor-pointer gap-4 overflow-hidden rounded-2xl border border-white/[.07] bg-dark-900/65 text-left transition hover:border-primary-500/30 ${sortable.isDragging?'z-20 opacity-60 shadow-2xl':''} ${grid || dense ? 'flex-col items-stretch p-2.5' : 'min-h-24 items-center p-3'}`}><Collage urls={playlist.cover_urls} customUrl={playlist.cover_file_id ? playlist.cover_url : null} large={grid || dense}/><span dir="rtl" className="min-w-0 flex-1 text-right"><strong dir="auto" className={`block truncate ${grid ? 'text-lg' : dense ? 'text-sm' : 'text-base'}`}>{playlist.name}</strong><span className={`mt-2 flex gap-1.5 ${dense ? 'flex-col' : 'flex-wrap'}`}><span className="rounded-full bg-white/[.05] px-2 py-1 text-[11px] text-dark-300">🎵 {playlist.item_count.toLocaleString('fa-IR')} ترک</span>{!dense && <span className="rounded-full bg-white/[.05] px-2 py-1 text-[11px] text-dark-300">⏱️ {formatDuration(playlist.total_duration) || 'نامشخص'}</span>}</span><span className={`mt-2 gap-1 ${grid ? 'grid' : 'hidden sm:grid'}`}>{playlist.preview_names?.length ? playlist.preview_names.slice(0,2).map((name,index) => <span key={index} dir="auto" className="truncate text-[11px] text-dark-500">♪ {name}</span>) : <span className="text-[11px] text-dark-500">هنوز ترکی اضافه نشده</span>}</span></span>{manual && <button {...sortable.attributes} {...sortable.listeners} onPointerDown={event => event.stopPropagation()} onClick={event => event.stopPropagation()} className="flex h-10 w-8 shrink-0 touch-none items-center justify-center rounded-lg text-dark-500 hover:bg-white/[.05] hover:text-white" title="برای تغییر ترتیب بکش"><GripVertical className="h-5 w-5"/></button>}</article>;
}

function CoverTile({ src, className = '' }: { src: string; className?: string }) {
    const [failed, setFailed] = useState(false);
    useEffect(() => setFailed(false), [src]);
    return failed ? <span className={`${className} flex items-center justify-center bg-gradient-to-br from-primary-500/25 via-dark-800 to-pink-500/20 text-2xl`}>🎶</span> : <img loading="lazy" decoding="async" src={src} style={{ imageRendering: 'auto' }} className={className} alt="" onError={() => setFailed(true)}/>;
}

function Collage({ urls, customUrl, large = false }: { urls: string[]; customUrl?: string | null; large?: boolean }) {
    const token = localStorage.getItem('access_token');
    const auth = (url: string) => `${url}${url.includes('?') ? '&' : '?'}token=${encodeURIComponent(token || '')}`;
    return <span className={`grid shrink-0 grid-cols-2 overflow-hidden rounded-xl bg-gradient-to-br from-primary-500/30 to-pink-500/20 shadow-lg shadow-black/20 ${large ? 'aspect-square w-full' : 'h-16 w-16'}`}>{customUrl ? <CoverTile src={auth(customUrl)} className="col-span-2 h-full w-full object-cover"/> : urls.length ? urls.slice(0,4).map((url,i) => <CoverTile key={i} src={auth(url)} className="h-full w-full object-cover"/>) : <span className="col-span-2 flex items-center justify-center bg-gradient-to-br from-primary-500/20 via-dark-800 to-pink-500/20 text-3xl">🎶</span>}</span>;
}

function CoverPreview({ playlist }: { playlist: Playlist }) {
    const token = localStorage.getItem('access_token');
    const [failed, setFailed] = useState(false);
    useEffect(() => setFailed(false), [playlist.cover_url]);
    if (!playlist.cover_file_id || !playlist.cover_url || failed) return <span className="block h-52 w-52 overflow-hidden rounded-2xl shadow-2xl shadow-black/40"><Collage urls={playlist.cover_urls} large/></span>;
    return <span className="block h-52 w-52 shrink-0 overflow-hidden rounded-2xl bg-dark-800 shadow-2xl shadow-black/40"><img loading="eager" decoding="async" src={`${playlist.cover_url}${playlist.cover_url.includes('?')?'&':'?'}token=${encodeURIComponent(token || '')}`} style={{ imageRendering: 'auto' }} className="h-full w-full object-cover" alt="کاور پلی‌لیست" onError={() => setFailed(true)}/></span>;
}

function PlaylistDetail({ id, onBack }: { id: number; onBack: () => void }) {
    const readOnlyWorkspace = Boolean(localStorage.getItem('komod-active-workspace')) && localStorage.getItem('komod-active-workspace-permission') === 'read';
    const { data: playlist, isLoading } = usePlaylist(id);
    const reorder = useReorderPlaylist(); const shuffle = useShufflePlaylist(); const remove = useRemovePlaylistItem(); const del = useDeletePlaylist();
    const { startQueue, addToast, isPlayerMinimized, previewFile } = useAppStore();
    const [adding, setAdding] = useState(false); const [editing, setEditing] = useState(false); const [coverPicker, setCoverPicker] = useState(false); const [menu, setMenu] = useState(false); const [managing, setManaging] = useState(() => new URLSearchParams(location.search).get('manage') === '1'); const [selected, setSelected] = useState<Set<number>>(new Set()); const [activeItem, setActiveItem] = useState<number | null>(null); const [orderedItems, setOrderedItems] = useState<PlaylistItem[]>([]);
    useEffect(() => { if (playlist) setOrderedItems(playlist.items); }, [playlist]);
    const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 4 } }), useSensor(TouchSensor, { activationConstraint: { delay: 80, tolerance: 5 } }));
    if (isLoading || !playlist) return <div className="m-6 h-52 animate-pulse rounded-3xl bg-dark-800"/>;
    const play = (index = 0) => startQueue(orderedItems.map(x => x.file), index);
    const toggleSelected = (itemId: number) => setSelected(previous => { const next = new Set(previous); next.has(itemId) ? next.delete(itemId) : next.add(itemId); return next; });
    const selectAll = () => setSelected(selected.size === orderedItems.length ? new Set() : new Set(orderedItems.map(item => item.id)));
    const playSelected = () => { const files = orderedItems.filter(item => selected.has(item.id)).map(item => item.file); if (files.length) startQueue(files, 0); };
    const saveSelectedOffline = async () => { const files = orderedItems.filter(item => selected.has(item.id)).map(item => item.file); if (!files.length) return; try { await Promise.all(files.map(file => saveFileOffline(file))); addToast(`${files.length.toLocaleString('fa-IR')} فایل برای پخش آفلاین ذخیره شد 📥`); } catch { addToast('ذخیره آفلاین بعضی فایل‌ها انجام نشد', 'error'); } };
    const deleteSelected = async () => { try { await Promise.all([...selected].map(itemId => remove.mutateAsync({ id, itemId }))); setSelected(new Set()); setManaging(false); } catch { addToast('حذف بعضی ترک‌ها انجام نشد', 'error'); } };
    const dragEnd = async ({ active, over }: DragEndEvent) => { setActiveItem(null); if (readOnlyWorkspace || !over || active.id === over.id) return; const old = orderedItems.findIndex(x => x.id === active.id); const next = orderedItems.findIndex(x => x.id === over.id); const nextItems = arrayMove(orderedItems, old, next); setOrderedItems(nextItems); try { await reorder.mutateAsync({ id, itemIds: nextItems.map(x => x.id) }); } catch { setOrderedItems(playlist.items); addToast('ذخیرهٔ ترتیب انجام نشد', 'error'); } };
    const requestDelete = () => { const run = async () => { await del.mutateAsync(id); addToast('پلی‌لیست حذف شد'); onBack(); }; const message=`پلی‌لیست «${playlist.name}» حذف شود؟ فایل‌ها باقی می‌مانند.`; telegram()?.showConfirm ? telegram().showConfirm(message, (yes: boolean) => yes && void run()) : confirm(message) && void run(); };
    return <div className="mx-auto w-full max-w-5xl p-4 pb-28 sm:p-6 md:pb-8 lg:p-8">
        {managing ? <div className="mb-4 flex items-center gap-3 border-b border-white/[.06] pb-3"><button className="btn-icon" onClick={() => { setManaging(false); setSelected(new Set()); }} aria-label="بازگشت"><X className="h-5 w-5"/></button><strong className="text-lg">{selected.size.toLocaleString('fa-IR')} انتخاب‌شده</strong><button className="mr-auto rounded-xl border border-white/10 px-3 py-1.5 text-xs text-dark-200" onClick={selectAll}>{selected.size === orderedItems.length ? 'لغو انتخاب همه' : 'انتخاب همه'}</button></div> : <><div className="mb-5 flex h-12 items-center justify-between border-b border-white/[.07] px-1"><button className="flex h-9 w-9 items-center justify-center rounded-xl text-primary-200 transition hover:bg-primary-500/15 active:scale-95 md:invisible" onClick={onBack} title="بازگشت" aria-label="بازگشت به پلی‌لیست‌ها"><ChevronRight className="h-5 w-5"/></button>{!readOnlyWorkspace && <button className="flex h-9 w-9 items-center justify-center rounded-xl text-primary-200 transition hover:bg-primary-500/15 active:scale-95" onClick={() => setMenu(true)} aria-label="گزینه‌های پلی‌لیست"><MoreVertical className="h-5 w-5"/></button>}</div><header className="relative flex flex-col items-center gap-5 p-2 text-center"><CoverPreview playlist={playlist}/><div className="min-w-0 w-full"><div className="flex items-center justify-center gap-2"><h1 dir="auto" className="truncate text-3xl font-black">{playlist.name}</h1></div>{playlist.description && <p dir="auto" className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-dark-300">{playlist.description}</p>}<div className="mx-auto mt-3 flex w-fit items-center gap-2 rounded-full bg-white/[.05] px-3 py-1.5 text-xs text-dark-300"><span>🎵 {playlist.item_count.toLocaleString('fa-IR')} ترک</span><span className="h-1 w-1 rounded-full bg-white/20"/><span>⏱️ {formatDuration(playlist.total_duration) || 'نامشخص'}</span></div><div className="mx-auto mt-5 grid w-full max-w-xl grid-cols-2 gap-2"><button disabled={!orderedItems.length} className="btn-primary flex h-11 items-center justify-center gap-2 rounded-full !border-0 outline-none ring-0" title="پخش همه" onClick={() => play()}><Play className="h-4 w-4"/> پخش همه</button><button disabled={orderedItems.length < 2} className="btn-secondary flex h-11 items-center justify-center gap-2 rounded-full !border-0 outline-none ring-0" title="شافل" onClick={async () => { if (readOnlyWorkspace) { const files=[...orderedItems].sort(()=>Math.random()-.5).map(item=>item.file); if(files.length) startQueue(files,0); } else await shuffle.mutateAsync(id); }}><Shuffle className="h-4 w-4"/> شافل همه</button></div></div></header></>}
        <DndContext sensors={sensors} collisionDetection={closestCenter} onDragStart={({ active }) => setActiveItem(Number(active.id))} onDragCancel={() => setActiveItem(null)} onDragEnd={dragEnd}><SortableContext items={orderedItems.map(x => x.id)} strategy={verticalListSortingStrategy}><div className="mt-5">{orderedItems.map((item,index) => <TrackRow key={item.id} item={item} manage={managing} selected={selected.has(item.id)} onToggle={() => toggleSelected(item.id)} onPlay={() => play(index)} onLongPress={() => { if (!readOnlyWorkspace) { setManaging(true); setSelected(new Set([item.id])); } }}/>)}</div></SortableContext><DragOverlay>{activeItem ? <div className="rounded-xl border border-primary-500/40 bg-dark-800 px-4 py-3 shadow-2xl">{orderedItems.find(item => item.id === activeItem)?.file.file_name}</div> : null}</DragOverlay></DndContext>
        {!orderedItems.length && <button disabled={readOnlyWorkspace} onClick={() => setAdding(true)} className="mt-5 w-full rounded-2xl border border-dashed border-white/10 py-14 text-dark-300 disabled:cursor-default">این پلی‌لیست هنوز خالیه! {!readOnlyWorkspace && <span className="mt-2 block text-primary-300">➕ افزودن اولین آهنگ یا ویدیو</span>}</button>}
        {managing && <div className={`fixed inset-x-0 z-[130] mx-auto flex max-w-3xl items-center justify-around border-t border-white/10 bg-dark-900/95 px-2 py-3 shadow-2xl backdrop-blur-xl ${isPlayerMinimized && previewFile && (previewFile.file_type === 'audio' || previewFile.file_type === 'video') ? 'bottom-[calc(10rem+env(safe-area-inset-bottom))] md:bottom-20' : 'bottom-[calc(5rem+env(safe-area-inset-bottom))] md:bottom-0'}`}><button className="flex flex-col items-center gap-1 text-xs text-dark-200" onClick={() => setAdding(true)}><Plus className="h-5 w-5"/> افزودن به</button><button className="flex flex-col items-center gap-1 text-xs text-dark-200" onClick={playSelected}><Play className="h-5 w-5"/> پخش بعدی</button><button disabled={!selected.size} className="flex flex-col items-center gap-1 text-xs text-dark-200 disabled:opacity-30" onClick={() => void saveSelectedOffline()}><DownloadCloud className="h-5 w-5"/> دانلود</button><button className="flex flex-col items-center gap-1 text-xs text-dark-200" onClick={() => { navigator.clipboard?.writeText(window.location.href); addToast('پیوند پلی‌لیست کپی شد'); }}><Share2 className="h-5 w-5"/> اشتراک</button><button disabled={!selected.size} className="flex flex-col items-center gap-1 text-xs text-red-300 disabled:opacity-30" onClick={() => void deleteSelected()}><Trash2 className="h-5 w-5"/> حذف</button></div>}
        {menu && <div className="fixed inset-0 z-[140] flex items-end bg-black/60 backdrop-blur-sm" onClick={() => setMenu(false)}><div className="w-full rounded-t-3xl border-t border-white/10 bg-dark-900 p-4 pb-[calc(1rem+env(safe-area-inset-bottom))]" onClick={event => event.stopPropagation()}><div className="mx-auto mb-4 h-1 w-12 rounded-full bg-white/20"/><button className="context-menu-item min-h-14 w-full py-4 text-base" onClick={() => { setEditing(true); setMenu(false); }}><Pencil className="h-5 w-5"/> تغییر نام</button><button className="context-menu-item min-h-14 w-full py-4 text-base" onClick={() => { setAdding(true); setMenu(false); }}><Plus className="h-5 w-5"/> افزودن فایل</button><button className="context-menu-item min-h-14 w-full py-4 text-base" onClick={() => { setCoverPicker(true); setMenu(false); }}><Image className="h-5 w-5"/> تغییر کاور</button><button className="context-menu-item min-h-14 w-full py-4 text-base" onClick={() => { setManaging(true); setMenu(false); }}><Check className="h-5 w-5"/> مدیریت</button><button className="context-menu-item min-h-14 w-full py-4 text-base text-red-300" onClick={() => { setMenu(false); requestDelete(); }}><Trash2 className="h-5 w-5"/> حذف پلی‌لیست</button></div></div>}
        {adding && <BulkAdd playlist={playlist} onClose={() => setAdding(false)}/>} {editing && <EditPlaylist playlist={playlist} close={() => setEditing(false)}/>} {coverPicker && <CoverPicker playlist={playlist} onClose={() => setCoverPicker(false)}/>} 
    </div>;
}

function TrackRow({ item, manage, selected, onToggle, onPlay, onLongPress }: { item: PlaylistItem; manage: boolean; selected: boolean; onToggle: () => void; onPlay: () => void; onLongPress: () => void }) {
    const sortable = useSortable({ id: item.id }); const token = localStorage.getItem('access_token');
    const [thumbnailFailed, setThumbnailFailed] = useState(false);
    const longPressTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const suppressClick = useRef(false);
    const thumbnail = item.file.thumbnail_url ? `${item.file.thumbnail_url}${item.file.thumbnail_url.includes('?') ? '&' : '?'}token=${encodeURIComponent(token || '')}` : null;
    const title = item.file.file_name.replace(/\.[^/.]+$/, '');
    const clearLongPress = () => { if (longPressTimer.current) { clearTimeout(longPressTimer.current); longPressTimer.current = null; } };
    const startLongPress = (event: React.PointerEvent) => { if (event.pointerType !== 'touch' || manage) return; suppressClick.current = false; longPressTimer.current = setTimeout(() => { suppressClick.current = true; onLongPress(); }, 500); };
    return <div dir="ltr" ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.isDragging ? undefined : sortable.transition }} onPointerDown={startLongPress} onPointerUp={clearLongPress} onPointerCancel={clearLongPress} onPointerLeave={clearLongPress} onClick={() => { if (suppressClick.current) { suppressClick.current = false; return; } manage ? onToggle() : onPlay(); }} className={`group flex min-h-[72px] cursor-pointer items-center gap-3 border-b border-white/[.06] px-1 py-3 transition-colors hover:bg-white/[.035] ${selected ? 'bg-primary-500/[.08]' : ''} ${sortable.isDragging ? 'z-10 opacity-60 shadow-xl' : ''}`}>
        <button {...sortable.attributes} {...sortable.listeners} onClick={event => event.stopPropagation()} className="flex h-11 w-8 shrink-0 touch-none items-center justify-center text-dark-500 hover:text-dark-200" title="برای جابه‌جایی بکش"><GripVertical className="h-5 w-5"/></button>
        {manage && <span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full border ${selected ? 'border-primary-400 bg-primary-500 text-white' : 'border-white/25 text-transparent'}`}><Check className="h-4 w-4"/></span>}
        <span className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-gradient-to-br from-primary-500/20 via-dark-800 to-pink-500/15 text-primary-200">{thumbnail && !thumbnailFailed ? <img loading="lazy" decoding="async" src={thumbnail} style={{ imageRendering: 'auto' }} alt="" className="h-full w-full object-cover" onError={() => setThumbnailFailed(true)}/> : item.file.file_type === 'video' ? <Film className="h-6 w-6"/> : <Music className="h-6 w-6"/>}</span>
        <span dir="auto" className="min-w-0 flex-1 text-right"><strong className="block truncate text-sm font-semibold text-white">{title}</strong><span className="mt-1 block truncate text-xs text-dark-500">{item.file.file_type === 'video' ? 'ویدیو' : 'صدا'} {item.file.duration ? `· ${formatDuration(item.file.duration)}` : ''}</span></span>
    </div>;
}

function BulkAdd({ playlist, onClose }: { playlist: Playlist; onClose: () => void }) {
    const [query,setQuery] = useState(''); const [folder,setFolder] = useState<number|null>(null); const [kind,setKind] = useState<Kind>('all'); const [selected,setSelected] = useState<Set<number>>(new Set());
    const { data } = useFiles(folder, kind === 'all' ? 'audio,video' : kind, query || undefined, 1, 'name:asc'); const { data: folders=[] } = useFolders(null); const add = useAddPlaylistItems();
    const existing = useMemo(() => new Set(playlist.items.map(x => x.file.id)), [playlist]);
    const submit = async () => { const ids=[...selected]; const duplicates=ids.filter(fileId => existing.has(fileId)); const run=async(allowDuplicates:boolean)=>{await add.mutateAsync({id:playlist.id,fileIds:ids,allowDuplicates});onClose()}; if (!duplicates.length) return run(false); const message='بعضی فایل‌ها قبلاً اضافه شده‌اند؛ دوباره هم اضافه شوند؟'; if(telegram()?.showConfirm) telegram().showConfirm(message,(yes:boolean)=>void run(yes)); else void run(confirm(message)); };
    const visibleFiles = data?.files || [];
    const selectableFiles = visibleFiles.filter(file => !existing.has(file.id));
    const allVisibleSelected = selectableFiles.length > 0 && selectableFiles.every(file => selected.has(file.id));
    const toggleAll = () => setSelected(previous => { const next = new Set(previous); visibleFiles.filter(file => !existing.has(file.id)).forEach(file => allVisibleSelected ? next.delete(file.id) : next.add(file.id)); return next; });
    return <div className="fixed inset-0 z-[150] flex items-end bg-black/70 backdrop-blur-sm" onClick={onClose}><div className="mx-auto flex max-h-[88vh] w-full max-w-2xl flex-col rounded-t-3xl border border-white/10 bg-dark-900 p-4 pb-[calc(1rem+env(safe-area-inset-bottom))]" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-3 h-1 w-12 rounded-full bg-white/20"/><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">افزودن فایل‌ها</h2><p className="mt-1 text-xs text-dark-500">فایل‌های صدا و ویدیو را انتخاب کن.</p></div><button className="btn-icon" onClick={onClose}><X className="h-5 w-5"/></button></div><div className="relative mt-4"><Search className="absolute right-3 top-3 h-4 w-4 text-dark-500"/><input className="input w-full pr-9" placeholder="جست‌وجوی آهنگ یا ویدیو…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="mt-3 grid grid-cols-3 rounded-xl border border-white/[.07] bg-dark-800/70 p-1">{([['all','همه'],['audio','🎵 آهنگ'],['video','🎬 ویدیو']] as [Kind,string][]).map(([value,label]) => <button key={value} onClick={() => setKind(value)} className={`rounded-lg px-2 py-2 text-xs ${kind === value ? 'bg-primary-500/20 text-primary-200' : 'text-dark-400'}`}>{label}</button>)}</div><CustomSelect className="mt-3" label="کشوی فایل‌ها" value={folder ?? 0} onChange={value => setFolder(value === 0 ? null : Number(value))} options={[{ value: 0, label: 'فایل‌های بیرون از کشو' }, ...folders.map(item => ({ value: item.id, label: item.name }))]}/><div className="mt-3 flex items-center justify-between border-b border-white/[.06] pb-2"><span className="text-xs text-dark-400">{selected.size.toLocaleString('fa-IR')} مورد انتخاب شده</span><button className="rounded-lg px-2 py-1 text-xs text-primary-300 hover:bg-primary-500/10" onClick={toggleAll}>{allVisibleSelected ? 'لغو انتخاب همه' : 'انتخاب همه'}</button></div><div className="min-h-0 flex-1 space-y-1 overflow-y-auto">{visibleFiles.map(file=><button key={file.id} disabled={existing.has(file.id)} onClick={()=>setSelected(prev=>{if(existing.has(file.id)) return prev; const n=new Set(prev);n.has(file.id)?n.delete(file.id):n.add(file.id);return n})} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-right disabled:cursor-not-allowed disabled:opacity-55 ${selected.has(file.id)?'border-primary-500/40 bg-primary-500/10':'border-transparent hover:bg-white/[.04]'}`}><span className={`h-5 w-5 rounded border ${selected.has(file.id)?'border-primary-400 bg-primary-500':'border-white/20'}`}/><span>{file.file_type==='video'?<Film className="h-4 w-4"/>:<Music className="h-4 w-4"/>}</span><span className="min-w-0 flex-1 truncate text-sm">{file.file_name}</span>{existing.has(file.id)&&<span className="text-[10px] text-amber-300">قبلاً افزوده شده</span>}</button>)}</div><button disabled={!selected.size||add.isPending} className="btn-primary mt-4" onClick={submit}>افزودن ({selected.size.toLocaleString('fa-IR')})</button></div></div>;
}

function CoverPicker({ playlist, onClose }: { playlist: Playlist; onClose: () => void }) {
    const { data } = useFiles(null, 'image', undefined, 1, 'created:desc', false, true);
    const update = useUpdatePlaylist(); const upload = useUploadFile();
    const uploadCover = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file || !file.type.startsWith('image/')) return; const uploaded = await upload.mutateAsync({ file, folderId: null }); await update.mutateAsync({ id: playlist.id, cover_file_id: uploaded.id }); onClose(); };
    return <div className="fixed inset-0 z-[160] flex items-end bg-black/70 backdrop-blur-sm" onClick={onClose}><div className="mx-auto max-h-[80vh] w-full max-w-2xl rounded-t-3xl border border-white/10 bg-dark-900 p-4" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-lg font-bold">انتخاب عکس پلی‌لیست</h2><div className="flex items-center gap-2"><label className="btn-secondary flex h-9 cursor-pointer items-center gap-1.5 px-3 text-xs"><Upload className="h-3.5 w-3.5"/> آپلود عکس<input type="file" accept="image/*" className="hidden" onChange={uploadCover} /></label><button className="btn-icon" onClick={onClose}><X className="h-5 w-5"/></button></div></div><div className="mt-4 grid max-h-[60vh] grid-cols-3 gap-3 overflow-y-auto sm:grid-cols-5">{(data?.files || []).map(file => <button key={file.id} disabled={update.isPending || upload.isPending} onClick={async () => { await update.mutateAsync({ id: playlist.id, cover_file_id: file.id }); onClose(); }} className={`overflow-hidden rounded-xl border ${playlist.cover_file_id === file.id ? 'border-primary-400 ring-2 ring-primary-500/30' : 'border-white/10'}`}><img loading="lazy" decoding="async" src={`${file.stream_url}${file.stream_url.includes('?') ? '&' : '?'}token=${encodeURIComponent(localStorage.getItem('access_token') || '')}`} className="aspect-square w-full object-cover"/><span className="block truncate p-1 text-[10px]">{file.file_name}</span></button>)}</div>{!data?.files.length && <p className="py-10 text-center text-sm text-dark-400">هنوز عکس تصویری در کمد نداری.</p>}</div></div>;
}

function EditPlaylist({ playlist, close }: { playlist: Playlist; close: () => void }) { const update=useUpdatePlaylist(); return <PlaylistEditor title="ویرایش پلی‌لیست" initialName={playlist.name} initialDescription={playlist.description||''} onClose={close} onSave={async(name,description)=>{await update.mutateAsync({id:playlist.id,name,description});close()}}/>; }
function PlaylistEditor({ title, initialName='', initialDescription='', onClose, onSave }: { title:string; initialName?:string; initialDescription?:string; onClose:()=>void; onSave:(name:string,description:string)=>Promise<void> }) {
    const [name,setName]=useState(initialName); const [description,setDescription]=useState(initialDescription); const [saving,setSaving]=useState(false);
    return <div className="fixed inset-0 z-[170] flex items-center justify-center bg-black/70 p-4" onClick={onClose}><form className="w-full max-w-md rounded-2xl border border-white/10 bg-dark-900 p-5" onClick={e=>e.stopPropagation()} onSubmit={async e=>{e.preventDefault();if(!name.trim())return;setSaving(true);try{await onSave(name.trim(),description.trim())}finally{setSaving(false)}}}>
        <div className="flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><button type="button" className="btn-icon" onClick={onClose}><X className="h-5 w-5"/></button></div><input autoFocus maxLength={255} className="input mt-4 w-full" placeholder="نام پلی‌لیست" value={name} onChange={e=>setName(e.target.value)}/><textarea maxLength={1024} className="input mt-3 min-h-24 w-full" placeholder="توضیحات (اختیاری)" value={description} onChange={e=>setDescription(e.target.value)}/><button disabled={saving||!name.trim()} className="btn-primary mt-4 flex w-full items-center justify-center gap-2"><Save className="h-4 w-4"/>{saving?'در حال ذخیره…':'ذخیره'}</button>
    </form></div>;
}
