import { useEffect, useState } from 'react';
import { Check, Pencil, Plus, Tags, Trash2, X } from 'lucide-react';
import { TagDefinition, useTagSettings, useUpdateTagSettings } from '../lib/api';
import CustomSelect from './CustomSelect';

export default function TagSettingsPanel(){
 const {data,isLoading}=useTagSettings(); const update=useUpdateTagSettings();
 const [tags,setTags]=useState<TagDefinition[]>([]); const [name,setName]=useState(''); const [color,setColor]=useState('#a855f7');
 const [editing,setEditing]=useState<string|null>(null); const [show,setShow]=useState(false); const [limit,setLimit]=useState(2);
 useEffect(()=>{if(data){setTags(data.tags);setShow(data.show_file_tags);setLimit(data.display_limit)}},[data]);
 const save=async(next=tags,nextShow=show,nextLimit=limit)=>{const result=await update.mutateAsync({tags:next.map(({name,color})=>({name,color})),show_file_tags:nextShow,display_limit:nextLimit});setTags(result.tags);setShow(result.show_file_tags);setLimit(result.display_limit)};
 const add=()=>{const clean=name.trim().replace(/^#/,'').slice(0,40);if(!clean)return;const next=[...tags.filter(tag=>tag.name.toLocaleLowerCase('fa')!==clean.toLocaleLowerCase('fa')),{name:clean,color,file_count:editing?tags.find(tag=>tag.name===editing)?.file_count||0:0}];void save(next);setName('');setEditing(null)};
 const beginEdit=(tag:TagDefinition)=>{setEditing(tag.name);setName(tag.name);setColor(tag.color)};
 return <div className="space-y-4"><section className="rounded-3xl border border-white/[.07] bg-dark-900/70 p-4 sm:p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-primary-500/15 text-primary-200"><Tags className="h-5 w-5"/></span><div><h2 className="font-bold">تگ‌های من</h2><p className="text-xs text-dark-400">فقط تگ‌هایی که خودت می‌سازی اینجا می‌مانند.</p></div></div><div className="mt-4 flex items-center gap-2"><label className="relative h-11 w-11 shrink-0 overflow-hidden rounded-xl border border-white/15" style={{backgroundColor:color}}><input type="color" value={color} onChange={event=>setColor(event.target.value)} className="absolute inset-[-10px] h-16 w-16 cursor-pointer opacity-0"/></label><input value={name} onChange={event=>setName(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')add()}} className="input min-w-0 flex-1" placeholder="نام تگ"/><button className="btn-primary flex h-11 items-center gap-1.5 px-3" onClick={add}>{editing?<Check className="h-4 w-4"/>:<Plus className="h-4 w-4"/>}<span className="hidden sm:inline">{editing?'ذخیره':'افزودن'}</span></button>{editing&&<button className="btn-icon" onClick={()=>{setEditing(null);setName('')}}><X className="h-4 w-4"/></button>}</div>{isLoading?<p className="mt-4 text-sm text-dark-500">در حال دریافت…</p>:tags.length===0?<p className="mt-4 rounded-2xl bg-white/[.035] p-4 text-center text-sm text-dark-500">هنوز تگی نساختی.</p>:<div className="mt-4 grid gap-2 sm:grid-cols-2">{tags.map(tag=><div key={tag.name} className="flex items-center gap-2 rounded-2xl border border-white/[.06] bg-dark-800/55 p-3"><span className="h-3 w-3 rounded-full" style={{backgroundColor:tag.color}}/><span className="min-w-0 flex-1 truncate text-sm">#{tag.name}</span><span className="rounded-full bg-white/[.05] px-2 py-1 text-[10px] text-dark-400">{(tag.file_count||0).toLocaleString('fa-IR')} فایل</span><button className="btn-icon h-8 w-8" onClick={()=>beginEdit(tag)}><Pencil className="h-3.5 w-3.5"/></button><button className="btn-icon h-8 w-8 text-red-300" onClick={()=>void save(tags.filter(item=>item.name!==tag.name))}><Trash2 className="h-3.5 w-3.5"/></button></div>)}</div>}</section><section className="rounded-3xl border border-white/[.07] bg-dark-900/70 p-4 sm:p-5"><h2 className="font-bold">نمایش زیر فایل‌ها</h2><label className="mt-4 flex cursor-pointer items-center justify-between rounded-2xl bg-dark-800/55 p-3"><span className="text-sm">نمایش تگ‌ها روی کارت فایل</span><input type="checkbox" checked={show} onChange={event=>{setShow(event.target.checked);void save(tags,event.target.checked,limit)}} className="h-5 w-5 accent-primary-500"/></label><CustomSelect className="mt-3" label="حداکثر تعداد قابل نمایش" value={limit} onChange={value=>{setLimit(Number(value));void save(tags,show,Number(value))}} options={[1,2,3,4,5,6].map(value=>({value,label:`${value.toLocaleString('fa-IR')} تگ`}))}/></section></div>
}
